common/models/User.php
<?php
namespace common\models;
use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $verification_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_PENDING = 0;
	const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;
	const STATUS_DELETED = 3;
	
	const ROLE_SUPER_ADMIN = 1;
	const ROLE_ADMIN = 2;
	
    const GENDER_MALE = 1;
	const GENDER_FEMALE = 2;
	
	const USER_STATUS = [
		0 => '<span class="btn btn-primary">Pending</span>',
		1 => '<span class="btn btn-success">Active</span>',
		2 => '<span class="btn btn-warning">Inactive</span>',
		3 => '<span class="btn btn-danger">Deleted</span>'
	];


	
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_INACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_INACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        //return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
        return static::findOne(['username' => $username]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds user by verification email token
     *
     * @param string $token verify email token
     * @return static|null
     */
    public static function findByVerificationToken($token) {
        return static::findOne([
            'verification_token' => $token,
            'status' => self::STATUS_INACTIVE
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Generates new token for email verification
     */
    public function generateEmailVerificationToken()
    {
        $this->verification_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }
	
	public static function getStatus()

    {

        return array(

            "" => 'Select Status',
            self::STATUS_PENDING => 'Pending',
            self::STATUS_ACTIVE => 'Active',
            self::STATUS_INACTIVE => 'Inactive',
            self::STATUS_DELETED => 'Deleted',

            );

    }
	
	public function loadAttributes(User $user)
    {
        // here is the magic happens
        $user->setAttributes([
            'email'    => $this->email,
            'username' => $this->username,
            'password' => $this->password
        ]);
    
    }
	
	public function beforeSave($insert) 
	{

		$time = strtotime($this->birthday);

		$time = date("Y-m-d", strtotime($this->birthday));

		$this->birthday = $time;

		return parent::beforeSave($insert);

		

	}


	public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'auth_key' => 'Auth Key',
            'password_hash' => 'Password Hash',
            'password_reset_token' => 'Password Reset Token',
            'email' => 'Email',
            'status' => 'Status',
            'verification_token' => 'Verification Token',
            'role' => 'Role',
            'gender' => 'Gender',
            'phone_number' => 'Phone Number',
            'updated_at' => 'Updated',
            'created_at' => 'Created',
        ];
    }
	
	
	public function getAllActiveUsers()
	{
		
		return User::find(['status'=>self::STATUS_ACTIVE]) ->andWhere(['<>','id',$this->id])->all();
	
	}
	
	public function getFullName()
	{

			return $this->first_name.' '.$this->last_name;

	}
	
	public function getRoleLabel()
	{

		if($this->account_type == self::ROLE_SUPER_ADMIN) {
			return "Super Admin";
		} else {
			return "Admin";
		}
		
		return "";
	
		
		
	}
	
	public static function getRoleLists()
    {

        return array(

            "" => 'Select Role',
            self::SUPER_ADMIN => 'Super Admin',
            self::ADMIN => 'Admin',

            );

    }
	public function getGenderText() 
	{
		$genderLists =[
			self::GENDER_MALE=> 'Male',
			self::GENDER_FEMALE=> 'Female',
		];
		
		return $genderLists[$this->gender];
	}
	
}

backend/views/admin/_change-password.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="user-form">
	
    <?php $form = ActiveForm::begin(); ?>
	
	<div class="row">
	
		<div class="col-md-12">
			<h4>Account Credential</h4>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'new_password')->passwordInput() ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'confirm_new_password')->passwordInput() ?>
		</div>
	</div>
	
	

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/admin/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="user-form">
	
    <?php $form = ActiveForm::begin(); ?>
	<div class="row">
		<div class="col-md-3">
			<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
		</div>
		

	</div>
	<div class="row">
		<div class="col-md-3">
			<?= $form->field($model, 'role')->dropDownList(
				array(""=>"Select Role")+array(
							1=>"Super Admin",
							2=>"Admin"
						)
			);
			?>
			
		</div>
	</div>
	
    
	<div class="row">
		<div class="col-md-3">
			<?= $form->field($model, 'gender')->dropDownList(
							array(
							""=>"Select Gender",
							1=>"Male",
							2=>"Female"
							)
						)
			?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'phone_number')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
		</div>
	</div>
	<div class="row">
	
		<div class="col-md-12">
			<h4>Account Credential</h4>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'password')->passwordInput() ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'confirm_password')->passwordInput() ?>
		</div>
	</div>
	
	

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/admin/_formUpdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="user-form">
	
    <?php $form = ActiveForm::begin(); ?>
	<div class="row">
		<div class="col-md-3">
			<?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
		</div>
		

	</div>
	<div class="row">
		<div class="col-md-3">
			<?= $form->field($model, 'role')->dropDownList(
				array(""=>"Select Role")+array(
							1=>"Super Admin",
							2=>"Admin"
						)
			);
			?>
			
		</div>
	</div>
	
    
	<div class="row">
		<div class="col-md-3">
			<?= $form->field($model, 'gender')->dropDownList(
							array(
							""=>"Select Gender",
							1=>"Male",
							2=>"Female"
							)
						)
			?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'phone_number')->textInput(['maxlength' => true]) ?>
		</div>
		<div class="col-md-3">
			<?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
		</div>
	</div>
	

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/admin/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'first_name') ?>

    <?= $form->field($model, 'last_name') ?>
    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'auth_key') ?>

  
    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/admin/change-password.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Admin Update: ' . $model->first_name.' '.$model->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Admin', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Change Password';
?>
<div class="user-update">


    <?= $this->render('_change-password', [
        'model' => $model
    ]) ?>

</div>

backend/views/admin/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Create Admin';
$this->params['breadcrumbs'][] = ['label' => 'Admin', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="admin-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model
    ]) ?>

</div>

backend/views/admin/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm; 

/* @var $this yii\web\View */
/* @var $searchModel backend\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Admins';
$this->params['breadcrumbs'][] = $this->title;


		
?>
<div class="user-index">
	<div class="row">
		<div class="col-md-12">
			<?= Html::a('Add', ['create'], ['class' => 'btn btn-success pull-right']) ?>
		</div>
	</div>

<div class="table-responsive">
<?php \yii\widgets\Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
			  'attribute' => 'full_name',
			  'format' => 'raw', 
				'value' =>function($data){
					return $data->fullName;
				}
			],
            'email:email',
            [
			   'attribute' => 'status',
			   'format' => 'raw',
			   'value' =>function($data){
				   $statusLabel = [
					   0 => '<span class="text-primary">Pending</span>',
					   1 => '<span class="text-success">Active</span>',
					   2 => '<span class="text-warning">Inactive</span>',
					   3 => '<span class="text-danger">Deleted</span>'
				   ];
				   
				   
				   return $statusLabel[$data->status];
			   },
			   'filter'=> Html::dropDownList('UserSearch[status]',$statusParams,$model->getStatuses(),['class' => 'form-control'])
			],
            [
			   'attribute' => 'role',
			   'format' => 'raw',
			   'value' =>function($data){
				   $roleLabel = [
					   1 => '<span class="text-primary">Super Admin</span>',
					   2 => '<span class="text-success">Admin</span>',
				   ];
				   
				   
				   return $roleLabel[$data->role];
			   },
			   'filter'=> Html::dropDownList('UserSearch[role]',$roleParams,$model->getRoleLists(),['class' => 'form-control'])
			],

            ['class' => 
				
				'yii\grid\ActionColumn', 
				'header'=>'Actions',
				'template' => '{view} {update} {activate} {change_password}',
				
				'buttons'=> [
					'activate' => function ($url, $model) {     

						return $model->status == $model::STATUS_PENDING ? Html::a('<span class="glyphicon glyphicon-check"></span>',"#", [
							'class'=>'btn-activate-role',
							'data-id'=>$model->id,
							'data-toggle'=>"modal",
							'data-target'=>"#activate-user-modal",
							'title' => Yii::t('yii', 'Activate')
							
						]): "";                                

					},
					
					'change_password' => function ($url, $model) {     

						return Html::a('<span class="glyphicon glyphicon-lock"></span>',['admin/change-password', 'id' => $model->id], [
							'data-id'=>$model->id,
							'title' => Yii::t('yii', 'Change Password')
							
						]);                                

					}
					
				]
			]
        ]
    ]); ?>
<?php \yii\widgets\Pjax::end(); ?>
</div>
	<div class="modal fade" id="activate-user-modal" role="dialog">
		<div class="modal-dialog">
	
		<!-- Modal content-->
		<form id="form-activate-user" >
			<div class="modal-content">
				<div class="modal-header">
				  <button type="button" class="close close-button-object" data-dismiss="modal">&times;</button>
				  <h4 class="modal-title">Activate User</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-md-12">
							<div class="alert alert-success alert-dismissible activate-user-message">
							  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							  <strong>Success!</strong> User has been activated.
							</div>
						</div>
					</div>
					<div class="row">
						<input type="hidden" name="User[id]" id="activate_user_id" />
						<input type="hidden" name="User[status]" value="<?php echo $model::STATUS_ACTIVE;?>" />
					
						<div class="col-md-10 col-md-offset-1">

							<div class="form-group">
								<label>Do you want to activate this User?</label>
							</div>
							
						</div>
					</div>
				</div>
				<div class="modal-footer">
				  <button type="button" class="btn btn-default btn-success activate-user-submit">Yes</button>
				</div>
			</div>
	  
		</form>
		</div>
	</div>
	
</div>

backend/views/admin/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Update Admin: ' . $model->first_name.' '.$model->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Admin', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">


    <?= $this->render('_formUpdate', [
        'model' => $model
    ]) ?>

</div>

backend/views/admin/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $model->first_name." ".$model->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Admin', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);


?>
	



<div class="user-view">
		<div class="row">
			<div class="col-md-12">
				<div class="row panel panel-default">
					<div class="container-fluid">	
						<div class="row">
							<div class="col-md-6">
								<h3>Personal Details</h3>
							</div
							><div class="col-md-6">
								<h3>
									<?php if(Yii::$app->user->identity->role == $model::SUPER_ADMIN || $model->id == Yii::$app->user->identity->id) {?>
										<?= Html::a('Update', ['update','id'=>$model->id], ['class' => 'btn btn-success pull-right']) ?>
										<?= Html::a('Change Password', ['change-password','id'=>$model->id], ['class' => 'btn btn-primary pull-right']) ?>
									<?php } ?>
								</h3>
							</div>
							<div class="col-md-8 col-md-offset-2">
								
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<th colspan="2">Basic Information</th>
									  </tr>
									</thead>
									
									<tbody>
										<tr>
											<td>Username</td>
											<td><?= $model->username ?></td>
										</tr>
										<tr>
											<td>First Name</td>
											<td><?= $model->first_name ?></td>
										</tr>
										<tr>
											<td>Last Name</td>
											<td><?= $model->last_name ?></td>
										</tr>
										<tr>
											<td>Email</td>
											<td><?= $model->email ?></td>
										</tr>
										<tr>
											<td>Role</td>
											<td><?= $model->roleLabel ?></td>
										</tr>
										<tr>
											<td>Gender</td>
											<td><?= $model->genderText ?></td>
										</tr>
										<tr>
											<td>Phone Number</td>
											<td><?= $model->phone_number ?></td>
										</tr>
										
									</tbody>
								</table>
								
								</br>
								
							</div>
							
						</div>
					</div>
				</div>
			</div>
			
		
			
				
		</div>	
	
</div>