common/models/GcashAccounts.php
<?php

namespace common\models;

use Yii;

class GcashAccounts extends \yii\db\ActiveRecord
{
	const STATUS_PENDING = 0;
	const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;
	const STATUS_DELETED = 3;
	const STATUS_DONE = 4;
	const STATUS_OVER_DUE = 5;
	const STATUS_CANCELLED = 6;
	const STATUS_DECLINED = 7;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'gcash_accounts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_date','status'], 'safe'],
            ['phone_number', 'required'],
            ['full_name', 'required'],
            ['customer_id', 'required'],
            ['email', 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'phone_number' => 'Phone number',
            'full_name' => 'Full Name',
            'customer_id' => 'Customer',
            'email' => 'Email',
        ];
    }
	
	public function getStatusText()
	{
		$statusLabel = [
			self::STATUS_ACTIVE => "<labe class='badge badge-success'>Active</label>",
			self::STATUS_INACTIVE => "<labe class='badge badge-warning'>Inactive</label>",
		];
		
		return $statusLabel[$this->status];
	}
}

backend/controllers/CustomerController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Customers;
use backend\models\CustomersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class CustomerController extends Controller
{
	const SUPER_ADMIN = 1;
	const ADMIN = 2;
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
		$model = new Customers();

		$searchModel = new CustomersSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->pagination = ['pageSize' => 15];
		$statusParams = "";
		
		if(isset(Yii::$app->request->queryParams['CustomersSearch']['status'])) {
			$statusParams = Yii::$app->request->queryParams['CustomersSearch']['status'];
		}
		
		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
			'statusParams' => $statusParams,
			'model' => $model,
		]);
		
    }

    public function actionView($id)
    {
		
		$model =  $this->findModel($id);
        return $this->render('view', [
            'model' => $model
        ]);
    }


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$addresses = $model->getUserAddress();

		
        if ($model->load(Yii::$app->request->post()) && $model->userUpdate($addresses )) {
			Yii::$app->session->setFlash('success',  "User has been updated!");
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'addresses' => $addresses,
        ]);
    }
	
	public function actionActivate($id)
    {

        $model = $this->findModel($id);
	
	
        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
			echo json_encode([
				'response'=>true,
				'message'=>"Success"
				
			]);
			exit;
			
        } else {
			
			 echo json_encode([
				'response'=>false,
				'message'=>"Failed"
				
			]);
			exit;
		}

       
    }
	public function actionApproveRegistration($id)
    {

        $model = $this->findModel($id);
	
        if ($model->approveRegistration()) {
			
			Yii::$app->session->setFlash('success',  "Registration approval has been successful.");
        } else {
			Yii::$app->session->setFlash('error',  "Failed to approve registration!");
		}
		return $this->redirect(['view', 'id' => $model->id]);

       
    }
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Customers::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
	public function actionFlushOldData()
    {		
		$date = date("Y-m-d", strtotime("-6 months"));
		$qrCodes = QrCodes::find()->where(['<','created',$date])->all();		
		$pumRelatedDocs = PumRelatedDocs::find()->where(['<','created',$date])->all();		
		$fileUploads = FileUploads::find()->where(['<','created',$date])->all();		
		TemperaturesCollections::deleteAll(['<','created',$date]);		
		Temperatures::deleteAll(['<','created',$date]);		
		// Scanned::deleteAll(['<','created',$date]);		
		PumFindings::deleteAll(['<','created',$date]);		
		Pum::deleteAll(['<','created',$date]);		
		CloseContacts::deleteAll(['<','created',$date]);		
		CloseContactsCollections::deleteAll(['<','created',$date]);		
		Checklists::deleteAll(['<','created',$date]);		
		ChecklistCollections::deleteAll(['<','created',$date]);		
		
		foreach($qrCodes as $qrCode){
			$path = Yii::getAlias('@frontend/web/qrcodes/'.$qrCode->uuid.".png");
			if (file_exists($path) && $qrCode->uuid != "") {
				unlink($path);
			}
			$qrCode->delete();
		}
		foreach($pumRelatedDocs as $pumRelatedDoc){
			$path = Yii::getAlias('@backend/web/uploads/pums/'.$pumRelatedDoc->filename);
			if (file_exists($path) && $pumRelatedDoc->filename != "") {
				unlink($path);
			}
			$pumRelatedDoc->delete();
		}
		
		foreach($fileUploads as $fileUpload){
			$path = Yii::getAlias('@backend/web/uploads/checklists/'.$fileUpload->filename);
			if (file_exists($path) && $fileUpload->filename != "") {
				unlink($path);
			}
			$fileUpload->delete();
		}
		
		
		
        return true;
		
    }
}

frontend/controllers/CustomerController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;

use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Addresses;
use app\models\Loans;
use app\models\Employments;
use common\models\Customers;
use yii\web\UploadedFile;
use conquer\select2\Select2Action;
date_default_timezone_set("Asia/Hong_Kong");
/**
 * Site controller
 */
class CustomerController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	

	
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionMyAccount()
    {
		$customer = $this->findModel(Yii::$app->user->identity->id);
		return $this->render('my-account',[
					'customer' => $customer
				]);
		
	
    }
	
	public function actionLoan()
    {
		$loans = new Loans();
		$applyLoan = $loans->getCheckCurrentLoanStatus();
		$pendingLoan = $loans->getAllPendingLoans();
		$activeLoan = $loans->getAllActiveLoans();
		$doneLoan = $loans->getAllDoneLoans();
		$overDueLoan = $loans->getAllOverDueLoans();
		return $this->render('loan',[
					'pendingLoan' => $pendingLoan,
					'activeLoan' => $activeLoan,
					'doneLoan' => $doneLoan,
					'applyLoan' => $applyLoan,
					'overDueLoan' => $overDueLoan
				]);
		
	
    }
	public function actionApplyLoan()
    {
		$model = new Loans();
		if ($model->load(Yii::$app->request->post()) && $model->applyLoan()) {
            Yii::$app->session->setFlash('success', 'Thank you for applying for loan. Please check your loan status regularly.');
            return $this->redirect(['loan']);
        }
		
		return $this->render('apply-loan',[
					'model' => $model,
				]);
		
	
    }
	public function actionUploadSignature()
    {
		 $result = array();
		 $imagedata = base64_decode($_POST['img_data']);
		 $filename = md5(date("dmYhisA"));
		 //Location to where you want to created sign image
		 $file_name = './doc_signs/'.$filename.'.png';
		 file_put_contents($file_name,$imagedata);
		 $result['status'] = 1;
		 $result['file_name'] = $filename.'.png';
		 echo json_encode($result);
		
	
    }
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new CustomerLoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current customers.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionSignup()
    {
		
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            Yii::$app->session->setFlash('success', 'Thank you for registration. Please check your inbox for verification email.');
            return $this->goHome();
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }
	public function actionUpdate()
    {
		$id = Yii::$app->user->identity->id;
        $model = $this->findModel($id);
		$addresses = $model->getUserAddress();
		$employments = $model->getUserEmployment();

		
        if ($model->load(Yii::$app->request->post()) && $model->customerUpdate($addresses,$employments )) {
			Yii::$app->session->setFlash('success',  "Account has been updated!");
            return $this->redirect(['customer/my-account', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'addresses' => $addresses,
            'employments' => $employments,
        ]);
    }
    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Verify email address
     *
     * @param string $token
     * @throws BadRequestHttpException
     * @return yii\web\Response
     */
    public function actionVerifyEmail($token)
    {
        try {
            $model = new VerifyEmailForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }
        if ($user = $model->verifyEmail()) {
            if (Yii::$app->user->login($user)) {
                Yii::$app->session->setFlash('success', 'Your email has been confirmed!');
                return $this->goHome();
            }
        }

        Yii::$app->session->setFlash('error', 'Sorry, we are unable to verify your account with provided token.');
        return $this->goHome();
    }

    /**
     * Resend verification email
     *
     * @return mixed
     */
    public function actionResendVerificationEmail()
    {
        $model = new ResendVerificationEmailForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
                return $this->goHome();
            }
            Yii::$app->session->setFlash('error', 'Sorry, we are unable to resend verification email for the provided email address.');
        }

        return $this->render('resendVerificationEmail', [
            'model' => $model
        ]);
    }
	
	
	protected function findModel($id)
    {
        if (($model = Customers::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
	
}

frontend/views/customer/_loan.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

?>

<div id="apply-loan-form">
	
    <?php $form = ActiveForm::begin(); ?>
	
	<div class="row">
		
		<div class="col-md-6 col-md-offset-3">
			<?= $form->field($model, 'amount')->textInput(['type' => 'number']) ?>
		</div>
		
	</div>
	<div class="row">
		
		<div class="col-md-6 col-md-offset-3">
			<?= $form->field($model, 'term')
								 ->dropDownList(
										array(
										""=>"Select Terms",
										3=>"3 Months",
										6=>"6 Months",
										9=>"9 Months",
										12=>"12 Months",
										)
									)
							?>
		</div>
		
	</div>
    <div class="row">
		
		
		<div class="col-md-6 col-md-offset-3">
			<?= $form->field($model, 'interest')->hiddenInput()->label(false) ?>
			<?= $form->field($model, 'interest_input')->textInput(['type' => 'number', 'value' => 0,'disabled' => true]) ?>
		</div>

	</div>
	<div class="row">
		
		<div class="col-md-6 col-md-offset-3">
			<?= $form->field($model, 'amortization')->hiddenInput()->label(false) ?>
			<?= $form->field($model, 'amortization_input')->textInput(['type' => 'number', 'value' => 0,'disabled' => true]) ?>
		</div>

	</div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="form-group">
				<?= Html::submitButton('Submit', ['class' => 'btn btn-success pull-right']) ?>
			</div>
		</div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/customer/apply-loan.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Apply Loan' ;
$this->params['breadcrumbs'][] = 'Apply Loan';
?>
<div class="apply-loan">


    <?= $this->render('_loan', [
        'model' => $model
    ]) ?>

</div>

frontend/views/customer/loan.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;


		
?>
<div class="site-index">
	<div class="row padding-bottom-10">
		<div class="col-md-12">
			<?php 
				if(empty($applyLoan)) {
					echo Html::a('Apply Loan', ['apply-loan'], ['class' => 'btn btn-success pull-right']); 
				}
			

			?>
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<div class="container-fluid">	
				<div class="row panel panel-default">
					<div class="col-md-12">
						<h3>Pending Loan</h3>
					</div>
					<div class="col-md-12">
						<div class="table-responsive">
							<?= GridView::widget([
								'dataProvider' => $pendingLoan,
								'columns' => [
									
									[
									  'attribute' => 'amount'
									],
									[
									  'attribute' => 'amortization'
									],
									[
									  'attribute' => 'created'
									],
									['class' => 
										'yii\grid\ActionColumn', 
										'header'=>'Actions',
										'template' => '{view-pending-loan}',
										
										'buttons'=> [
											'view-pending-loan' => function ($url, $model) {     

												return Html::a('View', ['/loan/view', 'id' => $model->id],['target'=>'_blank']);                              

											}
											
										]
									]
								]
							]); ?>
							
							</br>
						
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-md-6">
			<div class="container-fluid">	
				<div class="row panel panel-default">
				
					<div class="col-md-12">
						<h3>Active Loan</h3>
					</div>
					<div class="col-md-12">
						<div class="table-responsive">
							<?= GridView::widget([
								'dataProvider' => $activeLoan,
								'columns' => [
									
									[
									  'attribute' => 'amount'
									],
									[
									  'attribute' => 'amortization'
									],
									[
									  'attribute' => 'created'
									],
									['class' => 
										'yii\grid\ActionColumn', 
										'header'=>'Actions',
										'template' => '{view-active-loan}',
										
										'buttons'=> [
											'view-active-loan' => function ($url, $model) {     

												return Html::a('View', ['/loan/view', 'id' => $model->id],['target'=>'_blank']);                              

											}
											
										]
									]
								]
							]); ?>
							
						</div>
					</div>
				</div>
			</div>
		</div>
		
			
	</div>	
	
	<div class="row">
		<div class="col-md-6">
			<div class="container-fluid">	
				<div class="row panel panel-default">
					<div class="col-md-12">
						<h3>Done Loan</h3>
					</div>
					<div class="col-md-12">
						<div class="table-responsive">
							<?= GridView::widget([
								'dataProvider' => $doneLoan,
								'columns' => [
									
									[
									  'attribute' => 'amount'
									],
									[
									  'attribute' => 'amortization'
									],
									[
									  'attribute' => 'created'
									],
									['class' => 
										'yii\grid\ActionColumn', 
										'header'=>'Actions',
										'template' => '{view-done-loan}',
										
										'buttons'=> [
											'view-done-loan' => function ($url, $model) {     

												return Html::a('View', ['/loan/view', 'id' => $model->id],['target'=>'_blank']);                              

											}
											
										]
									]
								]
							]); ?>
							
						
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="container-fluid">	
				<div class="row panel panel-default">
					<div class="col-md-12">
						<h3>Payment Due</h3>
					</div>
					<div class="col-md-12">
						<div class="table-responsive">
							<?= GridView::widget([
								'dataProvider' => $overDueLoan,
								'columns' => [
									
									[
									  'attribute' => 'amount'
									],
									[
									  'attribute' => 'amortization'
									],
									[
									  'attribute' => 'created'
									],
									['class' => 
										'yii\grid\ActionColumn', 
										'header'=>'Actions',
										'template' => '{view-over-due-loan}',
										
										'buttons'=> [
											'view-over-due-loan' => function ($url, $model) {     

												return Html::a('View', ['/loan/view', 'id' => $model->id],['target'=>'_blank']);                              

											}
											
										]
									]
								]
							]); ?>
							
						
						</div>
					</div>
				</div>
			</div>
		</div>
		
		
			
	</div>	
	
</div>

frontend/views/customer/my-account.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = $customer->first_name." ".$customer->middle_name." ".$customer->last_name;
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);


?>
	



<div class="user-view">
	<div class="row padding-bottom-10">
		<div class="col-md-12">
			<?= Html::a('Update Account', ['update'], ['class' => 'btn btn-success pull-right']) ?>
		</div>
	</div>
    <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="row panel panel-default">
					<div class="container-fluid">	
						<div class="row">
							<div class="col-md-12">
								<h3>Personal Details</h3>
							</div>
							<div class="col-md-6">
								
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<th colspan="2">Basic Information</th>
									  </tr>
									</thead>
									
									<tbody>
										<tr>
											<td>First Name</td>
											<td><?= $customer->first_name ?></td>
										</tr>
										<tr>
											<td>Middle Name</td>
											<td><?= $customer->middle_name ?></td>
										</tr>
										<tr>
											<td>Last Name</td>
											<td><?= $customer->last_name ?></td>
										</tr>
										<tr>
											<td>Age</td>
											<td><?= $customer->age ?></td>
										</tr>
										<tr>
											<td>Gender</td>
											<td><?= $customer->gender ?></td>
										</tr>
										<tr>
											<td>Birthday</td>
											<td><?= $customer->birthday ?></td>
										</tr>
										<tr>
											<td>Civil Status</td>
											<td><?= $customer->civilStatus ?></td>
										</tr>
									</tbody>
								</table>
								
								</br>
							</div>
							<div class="col-md-6">
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<th colspan="2">Address Details</th>
									  </tr>
									</thead>
									
									<tbody>
										<tr>
											<td>House Number</td>
											<td><?= $customer->address->house_number ?></td>
										</tr>
										<tr>
											<td>Street</td>
											<td><?= $customer->address->street ?></td>
										</tr>
										<tr>
											<td>Barangay</td>
											<td><?= $customer->address->barangay ?></td>
										</tr>
										<tr>
											<td>City</td>
											<td><?= $customer->address->city ?></td>
										</tr>
										<tr>
											<td>Province</td>
											<td><?= $customer->address->province ?></td>
										</tr>
										<tr>
											<td>Postal Code</td>
											<td><?= $customer->address->post_code ?></td>
										</tr>
									</tbody>
								</table>
								
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<?php 
										
										if($customer->employments->source_of_income != 4) { //Business Owner ?>
											<th colspan="3">Employment Details</th>
										<?php  } else { ?>
											<th colspan="1">Employment Details</th>
										<?php  } ?>
									  </tr>
									</thead>
									
									<tbody>
										<tr>
											<td>Source Of Income</td>
											<td><?= $customer->address->house_number ?></td>
										</tr>
										<?php if($customer->employments->source_of_income != 4) { //Business Owner ?>
										<tr>
											<td>Monthly Income</td>
											<td><?= $customer->employments->monthly_income ?></td>
										</tr>
										<tr>
											<td>Occupation</td>
											<td><?= $customer->employments->occupation ?></td>
										</tr>
										<?php  } ?>
									</tbody>
								</table>
								
							</div>
						</div>
					</div>
				</div>
			</div>
			
		
			
				
		</div>	
	</div>	
	
	<div class="container">	
		<div class="row panel panel-default">
			<div class="container">	
				<div class="col-md-6">
					<h3>GCASH Account</h3>
				</div>
				<div class="col-md-6">
					<h3>
						 <?php if ($customer->gcashAccount == null) { ?>
							<h3>
								<a href="/gcash/add" class="btn btn-success pull-right">Add Gcash Account</a>
							</h3>
					<?php } else { ?>
							<h3>
								<a href="/gcash/update?id=<?=$customer->gcashAccount->id?>" class="btn btn-success pull-right">Update Gcash Account</a>
							</h3>
					<?php } ?>
					</h3>
				</div>
				<table class="table table-striped  table-bordered">
					<thead>
					  <tr>
						<td>Full Name</td>
						<td>Phone Number</td>
						<td>Email</td>
						<td>Status</td>
					  </tr>
					</thead>
					
					<tbody>
						<?php 
								if($customer->gcashAccount != null) { ?>
									
									<tr>
										<td><?= $customer->gcashAccount->full_name ?></td>
										<td><?= $customer->gcashAccount->phone_number ?></td>
										<td><?= $customer->gcashAccount->email ?></td>
										<td><?= $customer->gcashAccount->statusText ?></td>
									</tr>
						<?php 		
								} else { ?>
								<tr>
									<td colspan="4">No found record.</td>
								</tr>
						<?php }
						?>
						
					</tbody>
				</table>

				</br>
			</div>

		</div>

	</div>
	
	<div class="container">	
		<div class="row panel panel-default">
			<div class="container">	
				<h3>Documents</h3>
				<table class="table table-bordered">
					<thead>
						<th>File</th>
						<th>Action</th>
					</thead>
					<tbody>
						<?php 
							
							if($customer->documents != null && $customer->signature != null) {
								foreach($customer->documents as $key => $value)
								{
									 
									$keyString = "";
									if($key == "valid_id") {
										$keyString="Valid ID";
									} else if($key == "secondary_id") {
										$keyString="Secondary ID";
									} else if($key == "proof_of_billing") {
										$keyString="Proof of Billing";
									}
									
									if($keyString != "") {
										echo "<tr>";
										
										echo "<td>".$keyString."</td>";
										echo "<td><a href=".Yii::getAlias('@web').'/uploads/customer/documents/'.$value." target='_blank'> View Docs</a></td>";
										echo "</tr>";
									}
								}
								
								echo "<tr>";
								echo "<td>Signature</td>";
								echo "<td><a href=".Yii::getAlias('@web').'/uploads/customer/signature/'.$customer->signature." target='_blank'> View Docs</a></td>";
								echo "</tr>";
								
							} else {
								echo "<tr><td colspan='2'>No found record.</td></tr>";
							}
						?>
						
					</tbody>
				</table>

				</br>
			</div>

		</div>

	</div>
	
	<div class="container">	
		<div class="row panel panel-default">
			<div class="container">	
				<h3>Additional Documents</h3>
				<table class="table table-bordered">
					<thead>
						<th>File</th>
						<th>Action</th>
					</thead>
					<tbody>
						<?php 
							if($customer->loans != null) {
								foreach ($customer->loans as $loans) { 
									foreach ($loans->loanAttachments as $attachment) { ?>
										<tr>
											<td><?= $attachment->filename ?></td>
											<td><a href="<?= Yii::getAlias('@web').'/uploads/customer/attachments/'.$attachment->path ?>" target="_blank"> View Docs</a></td>
										</tr>
					<?php 			}
								}
							} else { ?>
							<tr>
								<td colspan="2">No found record.</td>
							</tr>
					<?php }
					?>
						
					</tbody>
				</table>

				</br>
			</div>

		</div>

	</div>
	
	
	
	
</div>