common/models/Payments.php
<?php

namespace common\models;

use Yii;
use yii\web\UploadedFile;
use app\models\Loans;
class Payments extends \yii\db\ActiveRecord
{
	const STATUS_PENDING = 0;
	const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;
	const STATUS_DELETED = 3;
	const STATUS_DONE = 4;
	const STATUS_OVER_DUE = 5;
	const STATUS_CANCELLED = 6;
	const STATUS_DECLINED = 7;
	
	const PUBLIC_KEY = 'pk_test_c0e7bdc2c014a55fa9bf7feb4b87fef5';
	
	const PAYMENT_STATUS_PENDING = 0;
	const PAYMENT_STATUS_PAID = 1;
	const PAYMENT_STATUS_DUE = 2;
	const PAYMENT_STATUS_DECLINED = 3;
	
	const PAYMENT_TYPE_GCASH = 1;
	const PAYMENT_TYPE_REMITTANCE = 2;
    
	public $imageFile;
	
    public static function tableName()
    {
        return 'payments';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_date','remarks','slip','payment_type','request_id','payment_date','payment_status','status'], 'safe'],
            ['loan_id', 'required'],
            ['amount', 'required'],
            ['customer_id', 'required']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'loan_id' => 'Loan',
            'amount' => 'Amount',
            'customer_id' => 'Customer',
            'request_id' => 'Request ID',
            'remarks' => 'Remarks',
        ];
    }
	
	
	public function createPaymentRequest($loan)
	{
		
		$curl = curl_init();

		curl_setopt_array($curl, array(
		  CURLOPT_URL => 'https://g.payx.ph/payment_request',
		  CURLOPT_RETURNTRANSFER => true,
		  CURLOPT_ENCODING => '',
		  CURLOPT_MAXREDIRS => 10,
		  CURLOPT_TIMEOUT => 0,
		  CURLOPT_FOLLOWLOCATION => true,
		  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
		  CURLOPT_CUSTOMREQUEST => 'POST',
		  CURLOPT_POSTFIELDS => array(
			'x-public-key' => 'pk_test_c0e7bdc2c014a55fa9bf7feb4b87fef5',
			'amount' => $loan->amortization,
			'description' => 'Payment for loan'
		  ),
		));

		$response = json_decode(curl_exec($curl));

		curl_close($curl);
		$model = new Payments;
		$model->loan_id = $loan->id;
		$model->amount = $loan->amortization;
		$model->customer_id = $loan->customer_id;
		$model->request_id = $response->data->request_id;
		// $model->fee = $response->data->fee;
		// $model->description = $response->data->description;
		// $model->expiry = $response->data->expiry;
		$model->checkout_url = $response->data->checkouturl;
		$model->save(false);
		return $model;
	}
	public function removePayment()
	{
		$this->status = self::STATUS_DELETED;
		return $this->save(false);
	}
	public function getButton()
	{
		
		$button = '<a href="'.$this->checkout_url.'" target="_blank">
					<img src="https://getpaid.gcash.com/assets/img/paynow.png">
					</a>';
		return $button;
	}
	
	public function getPaymentStatusText()
	{
		$statusLabel = [
			self::PAYMENT_STATUS_PENDING => "<labe class='badge badge-warning'>PAYMENT PENDING</label>",
			self::PAYMENT_STATUS_PAID => "<labe class='badge badge-success'>PAYMENT PAID</label>",
			self::PAYMENT_STATUS_DUE => "<labe class='badge badge-danger'>PAYMENT DUE</label>",
		];
		
		return $statusLabel[$this->payment_status];
	}
	
	public function getPaymentTypeText()
	{
		$paymentType = [
			self::PAYMENT_TYPE_GCASH => "<labe class='badge badge-primary'>GCASH</label>",
			self::PAYMENT_TYPE_REMITTANCE => "<labe class='badge badge-success'>Remittance</label>",
		];
		
		return $paymentType[$this->payment_type];
	}
	
	public function addRemittanceSlip()
	{
		
		$this->imageFile = UploadedFile::getInstance($this, 'imageFile');
		$this->payment_type = self::PAYMENT_TYPE_REMITTANCE;
		$this->customer_id = Yii::$app->user->identity->id;
		
		if($this->imageFile != null) {				
			
			if(!file_exists(Yii::getAlias('@backend').'/web/uploads/customer/remittance/')) {
				mkdir(Yii::getAlias('@backend').'/web/uploads/customer/remittance/',0777,true);
			}
			if(!file_exists(Yii::getAlias('@frontend').'/web/uploads/customer/remittance/')) {
				mkdir(Yii::getAlias('@frontend').'/web/uploads/customer/remittance/',0777,true);
			}
			$path = "";
			if ($this->validate()) {
				$path = $this->imageFile->baseName."_" .date("Y-m-d-h-i-s"). '.' . $this->imageFile->extension;
				$this->imageFile->saveAs(Yii::getAlias('@frontend').'/web/uploads/customer/remittance/' .$path );
				$copied = copy(Yii::getAlias('@frontend').'/web/uploads/customer/remittance/' .$path  ,Yii::getAlias('@backend').'/web/uploads/customer/remittance/' .$path );
			} else {
				return false;
			}
			
			$this->slip = $path ;
			
			return $this->save(false);
			
			
		}
		
		return false;
		
		
	}
	
	public function verifyPayment()
	{
		$loan = Loans::findOne($this->loan_id);
		$loan->total_paid = $loan->total_paid + $this->amount;
		
		if($loan->total_paid >= $loan->total_due) {
			$loan->status = $loan::STATUS_DONE;
		}
		$this->payment_date =  date("Y-m-d h:i:sa");
		$this->status =  self::STATUS_DONE;
		
		return $this->save(false) && $loan->save(false) && $this->sendVerificationNotif($loan);
	}
	
	protected function sendVerificationNotif($loan)
    {
        return Yii::$app
            ->mailer
            ->compose(
                ['html' => 'verified-payment-html', 'text' => 'verified-payment-text'],
                ['loan' => $loan]
            )
            ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->name . ' robot'])
            ->setTo($loan->customer->email)
            ->setSubject('Payment Verified ' . Yii::$app->name)
            ->send();
    }
}

backend/controllers/LoanController.php
<?php

namespace backend\controllers;

use Yii;
use app\models\Loans;
use app\models\LoansSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

use MessageBird\Client;
use MessageBird\Objects\Message;
class LoanController extends Controller
{
	
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionIndex()
    {
		$model = new Loans();

		$searchModel = new LoansSearch();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		$dataProvider->pagination = ['pageSize' => 15];
		$statusParams = "";
		$termParams = "";
		
		if(isset(Yii::$app->request->queryParams['LoansSearch']['status'])) {
			$statusParams = Yii::$app->request->queryParams['LoansSearch']['status'];
		}
		if(isset(Yii::$app->request->queryParams['LoansSearch']['term'])) {
			$termParams = Yii::$app->request->queryParams['LoansSearch']['term'];
		}
		
		return $this->render('index', [
			'searchModel' => $searchModel,
			'dataProvider' => $dataProvider,
			'statusParams' => $statusParams,
			'termParams' => $termParams,
			'model' => $model,
		]);
		
    }

    public function actionView($id)
    {
		$model =  $this->findModel($id);
        return $this->render('view', [
            'model' => $model
        ]);
    }

	public function actionApprove($id)
    {

        $model = $this->findModel($id);
	
		$messageText = "Your loan has been approved.";
        if ($model->load(Yii::$app->request->post()) && $model->save(false) && $model->sendApproveLoanNotif() && $model->sendSms($messageText,$model->customer->phone_number)) {
			echo json_encode([
				'response'=>true,
				'message'=>"Success"
				
			]);
			exit;
			
        } else {
			
			 echo json_encode([
				'response'=>false,
				'message'=>"Failed"
				
			]);
			exit;
		}

       
    }
	
	public function actionDecline($id)
    {

        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->declineLoan()) {
			echo json_encode([
				'response'=>true,
				'message'=>"Success"
				
			]);
			exit;
			
        } else {
			
			 echo json_encode([
				'response'=>false,
				'message'=>"Failed"
				
			]);
			exit;
		}

       
    }
	
	public function actionAsk($id)
    {

        $model = $this->findModel($id);
		
        if ($model->load(Yii::$app->request->post()) && $model->askDetails()) {
			echo json_encode([
				'response'=>true,
				'message'=>"Success"
				
			]);
			exit;
			
        } else {
			
			 echo json_encode([
				'response'=>false,
				'message'=>"Failed"
				
			]);
			exit;
		}

       
    }
    protected function findModel($id)
    {
        if (($model = Loans::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
}

frontend/controllers/LoanController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;

use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\Addresses;
use app\models\Loans;
use app\models\Employments;
use common\models\Payments;
use common\models\Customers;
use yii\web\UploadedFile;
use conquer\select2\Select2Action;

use \DateTime;
date_default_timezone_set("Asia/Hong_Kong");

class LoanController extends Controller
{
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
	

	
	public function actionView($id)
    {
		$model =  $this->findModel($id);
		return $this->render('view',[
				'model' => $model
			]);
    }
	public function actionPayment($id)
    {
		$model =  $this->findModel($id);
		$payments = $model->activePayments;
		$newPayment = false;
		if( $payments != null) {
			$date1 = new DateTime($payments->created_date);
			$date2 = new DateTime();

			$diff = $date2->diff($date1);
			
			$hours = $diff->h;
			if($hours >= 6) {
				$payments->removePayment();
				$newPayment = true;
			}
		} else {
			$newPayment =true;
		}
		if($model->status == $model::STATUS_ACTIVE && $newPayment) {
			$paymentModel = new Payments;
			$payments = $paymentModel->createPaymentRequest($model);
			

		}
		
	
		$button = $payments->getButton();
		
		
		return $this->render('payment',[
				'model' => $model,
				'button' => $button,
			]);
    }
	
	public function actionRemittance($id)
	{
		$model =  $this->findModel($id);
		$paymentModel = new Payments;
		
		
		return $this->render('remittance',[
				'paymentModel' => $paymentModel,
				'model' => $model,
			]);
		
	}
	public function actionAddRemittance()
	{
		$postData = Yii::$app->request->post();
		$id = $postData['Payments']['loan_id'];
		$model =  $this->findModel($id);
		$paymentModel = new Payments;
		
		if ($paymentModel->load($postData) && $paymentModel->addRemittanceSlip()) {
			Yii::$app->session->setFlash('success', 'Remittance has been added.');
            return $this->redirect(['loan/view', 'id' => $id]);
		}
		foreach($paymentModel->errors as $error){
			Yii::$app->session->setFlash('error',$error);
		}
		
		
		return $this->redirect(['loan/remittance', 'id' => $id]);
		
	}
	
	public function actionAddAttachments()
    {
		$postData = Yii::$app->request->post();
		$id = $postData['Loans']['id'];
		$model =  $this->findModel($id);
		if ($model->load(Yii::$app->request->post()) && $model->addAttachments()) {
			Yii::$app->session->setFlash('success', 'File has been uploaded.');
            
		}
		return $this->redirect(['loan/view', 'id' => $id]);
		
    }
	
	public function actionCancel($id)
    {

        $model = $this->findModel($id);
	
	
        if ($model->load(Yii::$app->request->post()) && $model->save(false)) {
			echo json_encode([
				'response'=>true,
				'message'=>"Success"
				
			]);
			exit;
			
        } else {
			
			 echo json_encode([
				'response'=>false,
				'message'=>"Failed"
				
			]);
			exit;
		}

       
    }
	
	protected function findModel($id)
    {
        if (($model = Loans::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
	
	
}

frontend/views/loan/_remittance.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

?>

<div id="apply-loan-form">
	
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data'],'action'=>'add-remittance']); ?>
	
	<div class="row">
		
		<div class="col-md-6 col-md-offset-3">
			<?= $form->field($paymentModel, 'loan_id')->hiddenInput(['value'=>$model->id])->label(false); ?>
			<?= $form->field($paymentModel, 'amount')->textInput(['type' => 'number']) ?>
		</div>
		
	</div>
	<div class="row">
		
		<div class="col-md-6 col-md-offset-3">
			<?= $form->field($paymentModel, 'imageFile')->fileInput() ?>
		</div>
		
	</div>
	
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="form-group">
				<?= Html::submitButton('Submit', ['class' => 'btn btn-success pull-right']) ?>
			</div>
		</div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/loan/payment.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use yii\widgets\ActiveForm;


$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

 
?>
	


		
<div class="loan-view" id="loan-view-page">
	
    <div class="container">
		<div class="row">
			<div class="col-md-12">
				Pay now via Gcash!
			</div>	
			<div class="col-md-12">
				<?=$button?>
			</div>
			<div class="col-md-12">
				<i>Note*: Payment may take a while to take effect. If you already paid this transaction please ignore payment process and wait for the payment confirmation.
					Thank you for your kind consideration.
				</i>
			</div>
		</div>	
	</div>	
	
	
</div>

frontend/views/loan/remittance.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */

$this->title = 'Add Remittance Slip' ;
$this->params['breadcrumbs'][] = 'Add Remittance Slip';
?>
<div class="remittance-slip">


    <?= $this->render('_remittance', [
        'paymentModel' => $paymentModel,
        'model' => $model,
    ]) ?>

</div>

frontend/views/loan/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use yii\widgets\ActiveForm;


$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

?>
	


<div class="loan-view" id="loan-view-page">
	
    <div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="row panel panel-default">
					<div class="container-fluid">	
						<div class="row">
							<div class="col-md-6">
								<h3>Loan 
									<span>
									<?php if($model->status == $model::STATUS_ACTIVE) { ?>
										Reference: 1234-5678-91011 (remitance)
									<?php } ?>
									</span>
								
								</h3>
								
							</div>
							<div class="col-md-6">
								<?php if($model->status == $model::STATUS_PENDING) { ?>
									<h3>
										<a href="javascript:void(0)" class="btn btn-danger pull-right" data-toggle ="modal" data-target="#cancel-loan-modal" >Cancel Loan</a>
									</h3>
								<?php }?>
							</div>
							<div class="col-md-12">
								
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<th colspan="2">Loan Details</th>
									  </tr>
									</thead>
									
									<tbody>
										<tr>
											<td>Amount</td>
											<td><?= $model->amount ?></td>
										</tr>
										<tr>
											<td>Status</td>
											<td><?= $model->statusLabel ?></td>
										</tr>
										<tr>
											<td>Amortization</td>
											<td><?= $model->amortization ?></td>
										</tr>
										<tr>
											<td>interest</td>
											<td><?= $model->interest ?></td>
										</tr>
										<tr>
											<td>Term</td>
											<td><?= $model->term ?></td>
										</tr>
										<?php if( $model->total_paid > 0) { ?>
											<tr>
												<td>Total Paid</td>
												<td><?= $model->total_paid ?></td>
											</tr>
										<?php } ?>
										<tr>
											<td>Total Due</td>
											<td><?= $model->total_due ?></td>
										</tr>
										
										<tr>
											<td>Due Date</td>
											<td><?= $model->due_date ?></td>
										</tr>
									</tbody>
								</table>
								
								</br>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<h3>Remarks</h3>
							</div>
							
							<div class="col-md-12">
								
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<td>Remarks</td>
										<td>Created</td>
									  </tr>
									</thead>
									
									<tbody>
										<?php 
												if($model->loanRemarks != null) {
													foreach ($model->loanRemarks as $remark) { ?>
														<tr>
															<td><?= $remark->remarks ?></td>
															<td><?= $remark->created ?></td>
														</tr>
										<?php 		}
												} else { ?>
												<tr>
													<td colspan="2">No found record.</td>
												</tr>
										<?php }
										?>
										
									</tbody>
								</table>
								
								</br>
							</div>
						</div>
						
						<div class="row">
							<div class="col-md-6">
								<h3>Attachments</h3>
							</div>
							<div class="col-md-6">
								<?php if($model->status == $model::STATUS_PENDING) { ?>
								<h3>
									<a href="javascript:void(0)" class="btn btn-primary pull-right" data-toggle ="modal" data-target="#attachment-loan-modal" >Add Attachments</a>
								</h3>
								<?php } ?>
							</div>
							<div class="col-md-12">
								
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<td>File Name</td>
										<td>Action</td>
									  </tr>
									</thead>
									
									<tbody>
										<?php 
												if($model->loanAttachments != null) {
													foreach ($model->loanAttachments as $attachment) { ?>
														<tr>
															<td><?= $attachment->filename ?></td>
															<td><a href="<?= Yii::getAlias('@web').'/uploads/customer/attachments/'.$attachment->path ?>" target="_blank"> View Docs</a></td>
														</tr>
										<?php 		}
												} else { ?>
												<tr>
													<td colspan="2">No found record.</td>
												</tr>
										<?php }
										?>
										
									</tbody>
								</table>
								
								</br>
							</div>
						</div>
						<div class="row">
							<div class="col-md-6">
								<h3>Payments</h3>
							</div>
							<div class="col-md-6">
								 <?php if ($model->status == $model::STATUS_ACTIVE) { ?>
									<h3>
										<a href="/loan/payment?id=<?=$model->id?>" class="btn btn-primary pull-right">Pay Via Gcash</a>
									</h3>
									<h3>
										<a href="/loan/remittance?id=<?=$model->id?>" class="btn btn-success pull-right">Add Remitance Slip</a>
									</h3>
							<?php } ?>
							</div>
							<div class="col-md-12">
								
								<table class="table table-striped  table-bordered">
									<thead>
									  <tr>
										<td>Amount</td>
										<td>Payment Status</td>
										<td>Payment Date</td>
										<td>Payment Type</td>
										<td>Remarks</td>
									  </tr>
									</thead>
									
									<tbody>
										<?php 
												if($model->payments != null) {
													foreach ($model->payments as $payment) { ?>
														<tr>
															<td><?= $payment->amount ?></td>
															<td><?= $payment->paymentStatusText ?></td>
															<td><?= $payment->payment_date ?></td>
															<td><?= $payment->paymentTypeText ?></td>
															<td><?= $payment->remarks ?></td>
														</tr>
										<?php 		}
												} else { ?>
												<tr>
													<td colspan="5">No found record.</td>
												</tr>
										<?php }
										?>
										
									</tbody>
								</table>
								
								</br>
							</div>
						</div>
						
					</div>
				</div>
			</div>
			
		</div>	
	</div>	
	
	<div class="modal fade" id="cancel-loan-modal" role="dialog">
		<div class="modal-dialog">
	
		<!-- Modal content-->
		<form id="form-cancel-loan" >
			<div class="modal-content">
				<div class="modal-header">
				  <button type="button" class="close close-button-object" data-dismiss="modal">&times;</button>
				  <h4 class="modal-title">Cancellation of Loan</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-md-12">
							<div class="alert alert-success alert-dismissible cancel-loan-message">
							  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							  <strong>Success!</strong> Your loan has been cancelled.
							</div>
						</div>
					</div>
					<div class="row">
						<input type="hidden" name="Loans[id]" id="loan_id" value="<?php echo $model->id;?>" />
						<input type="hidden" name="Loans[status]" value="<?php echo $model::STATUS_CANCELLED;?>" />
					
						<div class="col-md-10 col-md-offset-1">

							<div class="form-group">
								<label>Do you want to cancel your loan?</label>
							</div>
							
						</div>
					</div>
				</div>
				<div class="modal-footer">
				  <button type="button" class="btn btn-default btn-success cancel-loan-submit">Yes</button>
				</div>
			</div>
	  
		</form>
		</div>
	</div>
	
	
	<div class="modal fade" id="attachment-loan-modal" role="dialog">
		<div class="modal-dialog">
	
		<!-- Modal content-->
		<?php $form = ActiveForm::begin(['action' => ['loan/add-attachments'],'options' => ['enctype' => 'multipart/form-data']]); ?>
			<div class="modal-content">
				<div class="modal-header">
				  <button type="button" class="close close-button-object" data-dismiss="modal">&times;</button>
				  <h4 class="modal-title">Add attachment</h4>
				</div>
				<div class="modal-body">
					<div class="row">
						<div class="col-md-12">
							<div class="alert alert-success alert-dismissible attachment-loan-message">
							  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
							  <strong>Success!</strong> File has been uploaded.
							</div>
						</div>
					</div>
						
					<div class="row">
						<?= $form->field($model, 'id')->hiddenInput(['value'=> $model->id])->label(false) ?>
						<div class="col-md-12">
							<?= $form->field($model, 'filename') ?>
							
						</div>
						<div class="col-md-12">
							<?= $form->field($model, 'imageFile')->fileInput() ?>
						</div>
					</div>
				</div>
				<div class="modal-footer">
					<?= Html::submitButton('Submit', ['class' => 'btn btn-success btn-submit']) ?>
				</div>
			</div>
	  
		<?php ActiveForm::end(); ?>
		</div>
	</div>
	
</div>